### ISSUE TITLE
[1.6.4]Startup Crash

### ISSUE THREAD

**Issue by axzxc1236** [TinyModularThings/TinyModularThings#14]
I don't know where is the problem, but remove TinyModularThings will solve the problem.
Crash log : https://gist.github.com/axzxc1236/6b187beea07478e01f15

> 	TinyModularThings{2.0.5} [TinyModularThings] (TinyModularThings Version 1.3.12.zip) Unloaded->Constructed->Pre-initialized->Errored

**Comment by Speiger** [comment]
@axzxc1236 id conflict, during loading. My mod give you the id what is crashing with in the normal log. Just search for [TinyModularThings] in the log and you find a crash.

**Comment by axzxc1236** [comment]
After I solved id conflict, this happens, and it doesn't loook like id conflict.
http://openeye.openmods.info/crashes/0b9bdb22d400e2c53f7d1c8c5a495393

**Comment by Speiger** [comment]
Yeah it is a critical error, for explaining:
I am looking through the OreDIctionary to remove stuff for something that i want to have... (Simply a force), but someone modifies the list while i am doing that... Well that causes a crash.
Good thing i made it possible that you can remove any plugin that you want (simply remove the folder inside of the Pluginfolder that you not want, nothing bad will happen since it is loading only things that are there), @axzxc1236 so remove the BC Addon in SpmodAPI and everything will be fine.
Only thing is that the Facades will not be implemented and also crafting recipes will be not loaded)...

**Comment by axzxc1236** [comment]
@Speiger After few tests, I found that Big Reactor caused this problem, probably because it makes IC2 Uranium Becomes Yellorite.

**Comment by axzxc1236** [comment]
@Speiger  I found it is EnderIO causing this crash.

**Comment by axzxc1236** [comment]
I don't know what is the Pluginfolder you said.
Remove BC addon in SpmodAPI?

**Comment by Speiger** [comment]
ok. The pluginfolder is inside of SpmodAPI/common. Do not delete that.
Go into the plugin folder. There is the pluginloader class and some folders.
And you delete the BC folder then you deinstalled a plugin.

Also the crash is caused by me, but i can not fix it now. But i will as soon as i have time.

That should fix your trouble.

**Comment by axzxc1236** [comment]
Thanks, problem solved :)
