### ISSUE TITLE
Please update this for 1.7.10 just a direct port of the 1.6 mod please specifically I just want SpmodAPI  for 1.7

### ISSUE THREAD

**Issue by crunkazcanbe** [TinyModularThings/TinyModularThings#15]
As the title says I miss this mod very bad

**Comment by Speiger** [comment]
SpmodAPI is in construction.
But the mod will be designed like the 1.4.7 version of it

**Comment by crunkazcanbe** [comment]
Will it have all the declarations like in the 1.6.4 version ? I love the hemp deco .

**Comment by Speiger** [comment]
@crunkazcanbe i am wokring on that.
Just to give you a couple infos.
The current version of SpmodAPI and TinyModularThings (AKA real TinyChest version) will be not released as sourcecode!
SpmodAPI has the current state:
-Hemp Blocks,
-BaseHemp Items,
-Cobble Stuff,
-Exp Stuff
-Hemp Plates,
-Circuits & Gears,
-Klostein (for english people SoapStone because they have a problem)
-Essens Items

Things todo:
-MobMachine,
-Squeezing Compressor,
-Enchanter
-AnimalGas Stuff
-AlphaTree
-Advanced Hemp Stuff
-Modded Plates
Etc..

So the progress is beeing done.
Atm SpmodAPI has a limited selfchoosen Testing Team (Aka some guys i choose to give a version)
When the release will be. No clue. But i am working on that since the last IC2 Classic release (about 5 days after that)

**Comment by Speiger** [comment]
@crunkazcanbe i did answer

**Comment by crunkazcanbe** [comment]
Well man If you need another tester I can run the mod and look for bugs to . I will also be willing to donate to you man ;because this is such a good mod ,and I miss it very much . When done do you think you could put it on curse ? Thanx man and wonderful mod I miss it .

**Comment by Speiger** [comment]
@crunkazcanbe curse.... I do not know. Maybe even never... I like to have control about my downloads.
But first release hmmm. If SpmodAPI and TinyChest is done. Maybe in 1 month or 2? Maybe longer?
I am not sure...

I was thinking about doing a Pateron or something. And People would get with a Special minimum a test version access^^" But not sure yet...

**Comment by crunkazcanbe** [comment]
How is SpmodAPI for 1.7.10 coming along ? Can we or I get a Alpha build to test for you ?

**Comment by Speiger** [comment]
Well i am not sure about releasing it... Oh well but i can say it is practily finish for its first beta release or full release. Its stable at 99% of the cases...

**Comment by crunkazcanbe** [comment]
Why would you not release it for everyone that loved the mod ?

:(



Sent using CloudMagic Email
[https://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.1.25&pv=5.1.1&source=email_footer_2] On Fri, Feb 19, 2016 at 4:18 PM, Speiger < notifications@github.com [notifications@github.com] > wrote:
Well i am not sure about releasing it... Oh well but i can say it is practily
finish for its first beta release or full release. Its stable at 99% of the
cases...

—
Reply to this email directly or view it on GitHub
[https://github.com/TinyModularThings/TinyModularThings/issues/15#issuecomment-186410635] .[https://github.com/notifications/beacon/AFZoAN6dc2FGTmr5riemj0NZpidD4dBoks5pl335gaJpZM4F9Q_Y.gif]

**Comment by Speiger** [comment]
Well main reason not sure if people would like it xD

**Comment by TTLPcraft** [comment]
i love this mod. :)

**Comment by Speiger** [comment]
@TTLPcraft you know if 5 people like it and the rest of the world hate it that shows the end result...
